<?php
define('LAN_NAVATAR_PREF_VAL_USERNAME', 'Username');
define('LAN_NAVATAR_PREF_VAL_REALNAME', 'Real Name');


// Project Info Menu
define('LAN_NAVATAR_INFO_MENU_TITLE', 'Project Info');
define('LAN_NAVATAR_INFO_MENU_SUBTITLE', 'Project on GitHub:');
define('LAN_NAVATAR_INFO_MENU_SUBTITLE_ISSUES', 'Report Issues:');
define('LAN_NAVATAR_INFO_MENU_ISSUES_TEXT', 'Click the issues button below to report your issues on Github.');
define('LAN_NAVATAR_INFO_MENU_SUBTITLE_DEV', 'Show your Appreciation!');
define('LAN_NAVATAR_INFO_MENU_SUPPORT_DEV_TEXT', 'If you find the plugin useful, please consider supporting what I do.');
define('LAN_NAVATAR_INFO_MENU_SUPPORT_DEV_TEXT_SIGN', 'However, if it breaks something please don\'t blame me! &mdash; Arun');

define('LAN_NAVATAR_TIDY_CONFIRM_ROLLBACK', 'Confirm rollback of [count] user record(s) to previous state in \'[user]\' database table.');
define('LAN_NAVATAR_TIDY_INFO', 'To reinstate e107\'s default avatar state, run this rollback routine before uninstalling the plugin. It will remove the database entries and files generated by this plugin.');
define('LAN_NAVATAR_TIDY_MES_WARN_TICK', 'Please tick confirm checkbox. Nothing changed.');
define('LAN_NAVATAR_TIDY_MES_SUC_FILES_REMOVED', 'File(s) associated with records removed.');
define('LAN_NAVATAR_TIDY_MES_SUC_RECORDS_REMOVED', 'Database Record(s) removed successfully');
define('LAN_NAVATAR_TIDY_MES_ERR_NO_RECORDS', 'Nothing to rollback.');
define('LAN_NAVATAR_TIDY_MES_WARN_FAIL_DELETE', 'The file(s) [files] failed deletion.');

